### ISSUE TITLE
UIButtonLabel view inaccessible

### ISSUE THREAD

**Issue by Kirow** [EFPrefix/EFCountingLabel#22]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [README.md](https://github.com/EFPrefix/EFCountingLabel/blob/master/README.md), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/EFPrefix/EFCountingLabel/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

#### Description

I need access to view with text, but it hidden with 
```swift
override open var titleLabel: UILabel? {
    get {
        return countingLabel
    }
}
```

underlying method
```swift
EFCountingButtonLabel.setTextValue(_ value: CGFloat) {
    button.setTitle(..., for: .normal)
}
```
writes to `UIButtonLabel`, not to `EFCountingLabel`

**Simple solution** will be just to remove `titleLabel` override from `EFCountingButton`. It does nothing anyway.

More complex **idea** - is to rewrite component and make counter as separate logical model. i.e. extract counting logic from `EFCountingLabel` to `EFCounting`. use `EFCounting` in `EFCountingButton` and `EFCountingLabel` similar to `EFCountingButtonLabel` in current implementation.

It could be that I will make pull request on weekends...

**Comment by Coeur** [comment]
I agree that there are issues with the current implementation:
- We can't set `titleLabel.textColor` or `titleLabel.font`.
- We can't retrieve the `titleLabel.text`.
- We can't have a multi-line button, because that would require access to `titleLabel!.sizeThatFits(...)`, as shown by https://stackoverflow.com/a/50575588/1033581

But removing the override would still leave the unintuitive behavior of countingLabel writing to titleLabel.
